---
title: C6318
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6318
helpviewer_keywords:
- C6318
ms.assetid: 3284a83e-bb8e-461c-adcc-cfc66ceea05e
ms.openlocfilehash: 2da61e999542703d9846d7bb581f1691ec80d0f5
ms.sourcegitcommit: a1676bf6caae05ecd698f26ed80c08828722b237
ms.translationtype: MT
ms.contentlocale: zh-TW
ms.lasthandoff: 09/29/2020
ms.locfileid: "91509186"
---
# <a name="c6318"></a>C6318

> 警告 C6318：定義錯誤 __try/ \_ _except：在例外狀況篩選條件運算式中使用常數 EXCEPTION_CONTINUE_SEARCH 或另一個評估為零的常數。 未執行例外狀況處理常式區塊中的程式碼

此警告表示，如果在此結構化例外狀況處理常式的受保護區塊中發生例外狀況，將不會處理例外狀況，因為常數 `EXCECPTION_CONTINUE_SEARCH` 會用於例外狀況篩選運算式中。

此程式碼相當於不含例外狀況處理常式區塊的受保護區塊，因為處理常式區塊不會執行。

## <a name="example"></a>範例

下列程式碼會產生這個警告：

```cpp
#include <excpt.h>
#include <stdio.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except (EXCEPTION_CONTINUE_SEARCH) // warning C6318
  {
    puts("Exception Occurred");
  }
}
```

若要更正這個警告，請使用下列程式碼：

```cpp
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except( (GetExceptionCode() == EXCEPTION_ACCESS_VIOLATION) ?
                EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH )
  {
    puts("Access violation");
  }
}
```

## <a name="see-also"></a>另請參閱

[try-except 語句](../cpp/try-except-statement.md)
