---
title: C6320
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6320
helpviewer_keywords:
- C6320
ms.assetid: fb9e568e-b3d4-4ce2-a276-a64ad74d7b1e
ms.openlocfilehash: 6c5c67eb40ca3373b623dddbbb3cbfe1f21dc69c
ms.sourcegitcommit: a1676bf6caae05ecd698f26ed80c08828722b237
ms.translationtype: MT
ms.contentlocale: zh-TW
ms.lasthandoff: 09/29/2020
ms.locfileid: "91508751"
---
# <a name="c6320"></a>C6320

> 警告 C6320：例外狀況篩選條件運算式是常數 EXCEPTION_EXECUTE_HANDLER。 這可能會遮罩不打算處理的例外狀況

此警告表示在 __except 區塊中使用 EXCEPTION_EXECUTE_HANDLER 常數的副作用。 在此情況下，_except 區塊中的語句 \_ 一律會執行來處理例外狀況，包括您不想在特定函式中處理的例外狀況。 建議您先檢查例外狀況，再進行處理。

## <a name="example"></a>範例

下列程式碼會產生此警告，因為 __except 區塊將會嘗試處理所有類型的例外狀況：

```cpp
#include <stdio.h>
#include <excpt.h>

void f(int *p)
{
   __try
   {
      puts("in try");
      *p = 13;  // might cause access violation exception
      // code ...
   }
   __except(EXCEPTION_EXECUTE_HANDLER) // warning
   {
      puts("in except");
      // code ...
   }
}
```

若要更正這個警告，請 `GetExceptionCode` 在處理之前使用檢查特定的例外狀況，如下列程式碼所示：

```cpp
#include <stdio.h>
#include <windows.h>
#include <excpt.h>

void f(int *p)
{
   __try
   {
      puts("in try");
      *p = 13;    // might cause access violation exception
      // code ...
   }
   __except(GetExceptionCode()==EXCEPTION_ACCESS_VIOLATION ?
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)
   {
      puts("in except");
      // code ...
   }
}
```

## <a name="see-also"></a>另請參閱

[try-except 語句](../cpp/try-except-statement.md)
